
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 13;
  public static final int IGUALIGUAL = 23;
  public static final int CADENA = 27;
  public static final int IGUAL = 22;
  public static final int DECIMAL = 25;
  public static final int RSTRING = 5;
  public static final int DIVISION = 15;
  public static final int RIMPRIMIR = 2;
  public static final int PARIZQ = 10;
  public static final int MAYORQUE = 19;
  public static final int CONCAT = 16;
  public static final int PARDER = 11;
  public static final int UMENOS = 28;
  public static final int POR = 14;
  public static final int RBOOLEAN = 6;
  public static final int DISTINTO = 21;
  public static final int EOF = 0;
  public static final int MENORIGUALQUE = 18;
  public static final int RFALSE = 8;
  public static final int MENORQUE = 17;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 26;
  public static final int RNUMBER = 3;
  public static final int ENTERO = 24;
  public static final int RDECLARE = 4;
  public static final int MAYORIGUALQUE = 20;
  public static final int RTRUE = 7;
  public static final int MAS = 12;
  public static final int PTCOMA = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RIMPRIMIR",
  "RNUMBER",
  "RDECLARE",
  "RSTRING",
  "RBOOLEAN",
  "RTRUE",
  "RFALSE",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "MAS",
  "MENOS",
  "POR",
  "DIVISION",
  "CONCAT",
  "MENORQUE",
  "MENORIGUALQUE",
  "MAYORQUE",
  "MAYORIGUALQUE",
  "DISTINTO",
  "IGUAL",
  "IGUALIGUAL",
  "ENTERO",
  "DECIMAL",
  "IDENTIFICADOR",
  "CADENA",
  "UMENOS"
  };
}

